version: '3.5'

networks:
  docker-hadoop-cluster-network:
    driver: bridge
    name: docker-hadoop-cluster-network

services:
  kdc:
    container_name: "kdc"
    hostname: kdc.kerberos.com
    image: sequenceiq/kerberos
    networks:
      - docker-hadoop-cluster-network
    environment:
      REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos.com

  master:
    image: ${DOCKER_HADOOP_IMAGE_NAME:-aljoscha/docker-hadoop-secure-cluster:latest}
    command: master
    depends_on:
      - kdc
    ports:
      - "50070:50070"
      - "50470:50470"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"
    hostname: master.docker-hadoop-cluster-network
    networks:
      - docker-hadoop-cluster-network
    environment:
      KRB_REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos.com

  slave1:
    image: ${DOCKER_HADOOP_IMAGE_NAME:-aljoscha/docker-hadoop-secure-cluster:latest}
    command: worker
    depends_on:
      - kdc
      - master
    container_name: "slave1"
    hostname: slave1.docker-hadoop-cluster-network
    ports:
      - "9901:9864"
      - "8041:8042"
    networks:
      - docker-hadoop-cluster-network
    environment:
      KRB_REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos.com

  slave2:
    image: ${DOCKER_HADOOP_IMAGE_NAME:-aljoscha/docker-hadoop-secure-cluster:latest}
    command: worker
    depends_on:
      - kdc
      - master
    container_name: "slave2"
    hostname: slave2.docker-hadoop-cluster-network
    ports:
      - "9902:9864"
      - "8042:8042"
    networks:
      - docker-hadoop-cluster-network
    environment:
      KRB_REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos.com
